// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.1
// source: ozon.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Формат: DD-MM-YYYY
	Date          string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemRequest) Reset() {
	*x = ItemRequest{}
	mi := &file_ozon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemRequest) ProtoMessage() {}

func (x *ItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ozon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemRequest.ProtoReflect.Descriptor instead.
func (*ItemRequest) Descriptor() ([]byte, []int) {
	return file_ozon_proto_rawDescGZIP(), []int{0}
}

func (x *ItemRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type ItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemResponse) Reset() {
	*x = ItemResponse{}
	mi := &file_ozon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemResponse) ProtoMessage() {}

func (x *ItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ozon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemResponse.ProtoReflect.Descriptor instead.
func (*ItemResponse) Descriptor() ([]byte, []int) {
	return file_ozon_proto_rawDescGZIP(), []int{1}
}

func (x *ItemResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NumCode       string                 `protobuf:"bytes,2,opt,name=num_code,json=numCode,proto3" json:"num_code,omitempty"`
	CharCode      string                 `protobuf:"bytes,3,opt,name=char_code,json=charCode,proto3" json:"char_code,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Nominal       int32                  `protobuf:"varint,5,opt,name=nominal,proto3" json:"nominal,omitempty"`
	Value         float64                `protobuf:"fixed64,6,opt,name=value,proto3" json:"value,omitempty"`
	VunitRate     float64                `protobuf:"fixed64,7,opt,name=vunit_rate,json=vunitRate,proto3" json:"vunit_rate,omitempty"`
	Date          string                 `protobuf:"bytes,8,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_ozon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_ozon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_ozon_proto_rawDescGZIP(), []int{2}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetNumCode() string {
	if x != nil {
		return x.NumCode
	}
	return ""
}

func (x *Item) GetCharCode() string {
	if x != nil {
		return x.CharCode
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetNominal() int32 {
	if x != nil {
		return x.Nominal
	}
	return 0
}

func (x *Item) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Item) GetVunitRate() float64 {
	if x != nil {
		return x.VunitRate
	}
	return 0
}

func (x *Item) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

var File_ozon_proto protoreflect.FileDescriptor

const file_ozon_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"ozon.proto\x12\fozon_service\"!\n" +
	"\vItemRequest\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\"8\n" +
	"\fItemResponse\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.ozon_service.ItemR\x05items\"\xc5\x01\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bnum_code\x18\x02 \x01(\tR\anumCode\x12\x1b\n" +
	"\tchar_code\x18\x03 \x01(\tR\bcharCode\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x18\n" +
	"\anominal\x18\x05 \x01(\x05R\anominal\x12\x14\n" +
	"\x05value\x18\x06 \x01(\x01R\x05value\x12\x1d\n" +
	"\n" +
	"vunit_rate\x18\a \x01(\x01R\tvunitRate\x12\x12\n" +
	"\x04date\x18\b \x01(\tR\x04date2O\n" +
	"\vOzonService\x12@\n" +
	"\aGetItem\x12\x19.ozon_service.ItemRequest\x1a\x1a.ozon_service.ItemResponseB@Z>github.com/L1irik259/TestForOzon/transport/genetation/go/v1;v1b\x06proto3"

var (
	file_ozon_proto_rawDescOnce sync.Once
	file_ozon_proto_rawDescData []byte
)

func file_ozon_proto_rawDescGZIP() []byte {
	file_ozon_proto_rawDescOnce.Do(func() {
		file_ozon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ozon_proto_rawDesc), len(file_ozon_proto_rawDesc)))
	})
	return file_ozon_proto_rawDescData
}

var file_ozon_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ozon_proto_goTypes = []any{
	(*ItemRequest)(nil),  // 0: ozon_service.ItemRequest
	(*ItemResponse)(nil), // 1: ozon_service.ItemResponse
	(*Item)(nil),         // 2: ozon_service.Item
}
var file_ozon_proto_depIdxs = []int32{
	2, // 0: ozon_service.ItemResponse.items:type_name -> ozon_service.Item
	0, // 1: ozon_service.OzonService.GetItem:input_type -> ozon_service.ItemRequest
	1, // 2: ozon_service.OzonService.GetItem:output_type -> ozon_service.ItemResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ozon_proto_init() }
func file_ozon_proto_init() {
	if File_ozon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ozon_proto_rawDesc), len(file_ozon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ozon_proto_goTypes,
		DependencyIndexes: file_ozon_proto_depIdxs,
		MessageInfos:      file_ozon_proto_msgTypes,
	}.Build()
	File_ozon_proto = out.File
	file_ozon_proto_goTypes = nil
	file_ozon_proto_depIdxs = nil
}
