// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.1
// source: ozon.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OzonService_GetItem_FullMethodName = "/ozon_service.OzonService/GetItem"
)

// OzonServiceClient is the client API for OzonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OzonServiceClient interface {
	GetItem(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (*ItemResponse, error)
}

type ozonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOzonServiceClient(cc grpc.ClientConnInterface) OzonServiceClient {
	return &ozonServiceClient{cc}
}

func (c *ozonServiceClient) GetItem(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (*ItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemResponse)
	err := c.cc.Invoke(ctx, OzonService_GetItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OzonServiceServer is the server API for OzonService service.
// All implementations must embed UnimplementedOzonServiceServer
// for forward compatibility.
type OzonServiceServer interface {
	GetItem(context.Context, *ItemRequest) (*ItemResponse, error)
	mustEmbedUnimplementedOzonServiceServer()
}

// UnimplementedOzonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOzonServiceServer struct{}

func (UnimplementedOzonServiceServer) GetItem(context.Context, *ItemRequest) (*ItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetItem not implemented")
}
func (UnimplementedOzonServiceServer) mustEmbedUnimplementedOzonServiceServer() {}
func (UnimplementedOzonServiceServer) testEmbeddedByValue()                     {}

// UnsafeOzonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OzonServiceServer will
// result in compilation errors.
type UnsafeOzonServiceServer interface {
	mustEmbedUnimplementedOzonServiceServer()
}

func RegisterOzonServiceServer(s grpc.ServiceRegistrar, srv OzonServiceServer) {
	// If the following call panics, it indicates UnimplementedOzonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OzonService_ServiceDesc, srv)
}

func _OzonService_GetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OzonServiceServer).GetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OzonService_GetItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OzonServiceServer).GetItem(ctx, req.(*ItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OzonService_ServiceDesc is the grpc.ServiceDesc for OzonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OzonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ozon_service.OzonService",
	HandlerType: (*OzonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetItem",
			Handler:    _OzonService_GetItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ozon.proto",
}
